const STATUS_MESSAGE = {
  REGISTER_LINK: "Success! You Account has been created!",
  REGISTER: "You have successfully registered",
  LOGGED_IN: "You have successfully logged in",
  TRACK_SAVED: "Track saved successfully",
  TRACK_TAG_USER_LIST: "Track tag user list",
  INTERNAL_SERVER_ERROR: "Internal server error.",
  INCORRECT_EMAIL: "Incorrect email address.",
  INCORRECT_PASSWORD: "Incorrect Password.",
  INCORRECT_TOKEN: "Incorrect reset password token.",
  FORGOT_MSG: "Reset password link sent. Check your inbox or spam folders. ",
  PASSWORD_UPDATED: "Success! Your password has been updated.",
  UNAUTHORIZED: "Unauthorized access",
  LOGGED_OUT: "Logout Successfully",
  SUCCESS: "data list fetch successfully",
  SOMETHING_WENT_WRONG: "Something went wrong",
  ZIP_NOT_FOUND: "Zip code does not exist. Please enter a valid U.S. zip code.",
  EMAIL_EXIST: "Email already exists",
  USER_NAME_EXIST: "Username already exists",
  UPLOAD_DATA: "Files uploaded successfully",
  ZONE_LIST: "Zone list fetch successfully",
  ZONE_DETAILS: "Zone details fetch successfully",
  GENRE_LIST: "Genree list fetch successfully",
  GENRE_DETAILS: "Genree details fetch successfully",
  FAVOURITE_STATUS: "favourite status updated successfully",
  FAVOURITE_LIST: "favourite list fetch successfully",
  RECENT_UPLOAD: "Recent upload list fetch successfully",
  MY_UPLOAD: "My upload list fetch successfully",
  ZONE_NOT_FOUND: "Zone not found with this name",
  TRACK_DETAILS: "Track details fetch successfully",
  TRACK_UPDATE: "Track details update successfully",
  TRACK_FAVOURITE: "Track add into favourites successfully",
  CHART_LIST: "Chart list fetch successfully",
  STATE_ZONE: "Zone list fetch successfully",
  STATE_TRENDING: "Trending State list fetch successfully",
  ZONE_TRENDING: "Trending Zone list fetch successfully",
  CHART_TRENDING: "Trending Zone list fetch successfully",
  CHART_SEARCH: "chart search result fetch successfully",
  CHART_DETAILS: "Chart details fetch successfully",
  CHART_TRACKS: "Chart tracks fetch successfully",
  FAVOURITE_TRACKS: "Favourite tracks fetch successfully",
  RECENT_TRACKS: "Recently played tracks fetch successfully",
  SEARCH_MSG: "Please enter something",
  CHART_HOME: "Chart home details fetch successfully",
  USER_PROFILE: "User profile details fetch successfully",
  LATEST_RELEASES: "Latest releases list fetch successfully",
  PASSWORD_CHANGE: "Password changed successfully",
  WRONG_PASSWORD: "Wrong password",
  PROFILE_UPDATE: "Profile updated successfully!",
  COPYRIGHT: "Copyright Infringement Claim Sent Successfully",
  USER_NOT_FOUND:
    "No user found with that username. Please enter a valid username.",
  NOTIFICATIONLIST: "Notification list fetch successfully",
  CREATOR_HOME: "Creator home data fetch successfully",
  LISTNERS_HOME: "Listners home data fetch successfully",
  LISTNERS_RELEASES: "Listners releases data fetch successfully",
  CREATOR_GENRE: "Creator genre list fetch successfully",
  TRACK_DELETE: "Track deleted successfully",
};

module.exports = STATUS_MESSAGE;
